# Generated by Django 4.1.1 on 2022-09-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("todo", "0002_alter_task_options")]

    operations = [
        migrations.AlterModelOptions(
            name="task", options={"ordering": ["is_done", "-created_date"]}
        )
    ]
